// fonts
import { dom, library } from "@fortawesome/fontawesome-svg-core";
import {
  faTimes,
  faTimesCircle,
  faPlus,
  faFlask,
  faBox,
  faCogs,
  faCopy,
  faGears,
  faCloudUploadAlt,
  faAngleLeft,
  faAngleRight,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faHistory,
  faSearch,
  faIdBadge,
  faKey,
  faLayerGroup,
  faProjectDiagram,
  faNetworkWired,
  faHdd,
  faUsers,
  faServer,
  faDatabase,
  faSlash,
  faEllipsisVertical,
} from "@fortawesome/free-solid-svg-icons";

import { faUbuntu, faWindows } from "@fortawesome/free-brands-svg-icons";

library.add(
  faTimes,
  faTimesCircle,
  faPlus,
  faFlask,
  faBox,
  faCogs,
  faCopy,
  faGears,
  faCloudUploadAlt,
  faAngleLeft,
  faAngleRight,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faHistory,
  faSearch,
  faIdBadge,
  faKey,
  faLayerGroup,
  faProjectDiagram,
  faNetworkWired,
  faHdd,
  faUsers,
  faUbuntu,
  faWindows,
  faServer,
  faDatabase,
  faSlash,
  faEllipsisVertical
);

dom.watch();
